#!/usr/bin/env ruby
# post-receive

# 1. Read STDIN (Format: "from_commit to_commit branch_name")
from, to, ref = ARGF.read.split " "

puts "DEBUG: CLITE: #{ref}"

if (ref =~ /prod$/) == nil
    puts "CLITE: skipping deploy for branch #{ref}"
else
    if (ref =~ /prod$/) >= 0
        puts "CLITE: pushing #{ref} to upstream (github)"
        result = `git push origin #{ref}`
        puts "DEBUG: CLITE: #{result}"
    end

    if ( ref =~ /refs\/tags/ ) == 0
        puts "CLITE: pushing new tag reference #{ref}"
        result = `git push --tags`
        puts "DEBUG: CLITE: #{result}"
    end
    upstream = `git config --get remote.origin.url`
    puts "DEBUG: upstream is: #{upstream}"
    puts "DEBUG: reference is: #{ref}"
    result = system '/home/mrg/Work/ci-lite/src/bin/cilite.sh', "#{upstream}", "#{ref}"
end


# 4.TODO: Deployment Tasks
# i.e.: Run Puppet Apply, Restart Daemons, etc
